# Generated by Django 5.0.7 on 2024-08-21 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="endOfRide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("requestID", models.CharField(max_length=50)),
                ("totalRideRate", models.IntegerField()),
                ("waitingCharges", models.IntegerField()),
                ("endOfRideDate", models.DateField()),
                ("endOfRideTime", models.TimeField()),
                ("emotionFeedback", models.CharField(max_length=100)),
                ("totalDistance", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="onGoingRide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("requestID", models.CharField(max_length=50)),
                ("minimumFare", models.IntegerField()),
                ("waitingFare", models.IntegerField()),
                ("onGoingRideDate", models.DateField()),
                ("onGoingRideTime", models.TimeField()),
                ("comment", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="tuktukResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("requestID", models.CharField(max_length=50)),
                ("responseTime", models.TimeField()),
                ("responseDate", models.DateField()),
                ("response", models.CharField(max_length=50)),
            ],
        ),
    ]
