# Generated by Django 5.0.7 on 2024-08-21 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="loginCredentials",
            fields=[
                (
                    "userID",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("EMail", models.EmailField(max_length=50, unique=True)),
                ("password", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="loginSession",
            fields=[
                (
                    "userID",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("userType", models.CharField(max_length=10)),
            ],
        ),
    ]
