# Generated by Django 5.0.7 on 2024-08-21 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="tuktukUserData",
            fields=[
                (
                    "userID",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("userName", models.CharField(max_length=50)),
                ("dateOfRegistration", models.DateField()),
            ],
        ),
    ]
