# Generated by Django 5.0.7 on 2024-08-22 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="fareEstimation",
            fields=[
                ("fareNO", models.IntegerField(primary_key=True, serialize=False)),
                ("minimumFare", models.IntegerField()),
                ("farePerKm", models.IntegerField()),
                ("waitingFare", models.IntegerField()),
                ("currentDateOfChange", models.DateField()),
                ("minimumKM", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="feedback",
            fields=[
                ("feedbackID", models.IntegerField(primary_key=True, serialize=False)),
                ("feedback", models.CharField(max_length=100)),
                ("feedbackDate", models.DateField()),
                ("userID", models.CharField(max_length=50)),
                ("driverID", models.CharField(max_length=50)),
                ("reply", models.CharField(max_length=100)),
                ("replyDate", models.DateField()),
                ("EMail", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="tuktukData",
            fields=[
                (
                    "VehicleRegNo",
                    models.CharField(max_length=15, primary_key=True, serialize=False),
                ),
                ("vehicleType", models.CharField(max_length=10)),
                ("vehicleFuelType", models.CharField(max_length=10)),
                ("manufacturedCompany", models.CharField(max_length=20)),
                ("Vcc", models.IntegerField()),
                ("manufactureYear", models.CharField(max_length=4)),
                ("RC", models.CharField(max_length=100)),
                ("vPhoto", models.CharField(max_length=100)),
                ("regDate", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="tuktukDriverAllot",
            fields=[
                (
                    "allotID",
                    models.CharField(max_length=8, primary_key=True, serialize=False),
                ),
                ("VehicleRegNo", models.CharField(max_length=12)),
                ("driverID", models.CharField(max_length=15)),
                ("allotDate", models.DateField()),
                ("status", models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name="tuktukDriverData",
            fields=[
                (
                    "driverID",
                    models.CharField(max_length=15, primary_key=True, serialize=False),
                ),
                ("driverName", models.CharField(max_length=20)),
                ("houseName", models.CharField(max_length=50)),
                ("placeName", models.CharField(max_length=50)),
                ("pincode", models.CharField(max_length=6)),
                ("phoneNumber", models.CharField(max_length=12)),
                ("gender", models.CharField(max_length=10)),
                ("dateOfBirth", models.DateField()),
                ("aadhar", models.CharField(max_length=12)),
                ("license", models.CharField(max_length=25)),
                ("driverPhoto", models.CharField(max_length=100)),
                ("dateOfRegistration", models.DateField()),
            ],
        ),
    ]
